### ISSUE TITLE
Document how to push a gem to rubygems

### ISSUE THREAD

**Issue by macumber** [urbanopt/urbanopt-core-gem#3]

**Comment by macumber** [comment]
Also give access on rubygems

**Comment by vtnate** [comment]
rubygems username: `vtnate`

**Comment by tanushree04** [comment]
rubygems username: `Tanushree `

**Comment by macumber** [comment]
relkont

**Comment by macumber** [comment]
benpolly1

**Comment by macumber** [comment]
tijcolem

**Comment by macumber** [comment]
Thanks all, I just realized that we have not pushed any URBANopt gems to rubygems.com so I can't give any of you access to anything yet.  There are good instructions on how to push gems to rubygems.com once you are ready: https://guides.rubygems.org/publishing/
